config/routes.rb
Jobby::Application.routes.draw do
  get "home/index"
  
  root :to => "home#index"
  
  resources :users
  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, :notice => 'Listing was successfully created.' }
        format.json { render :json => @listing, :status => :created, :location => @listing }
      else
        format.html { render :action => "new" }
        format.json { render :json => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, :notice => 'Listing was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h4>Add the Jobby button and click it to save a job listing from any site.</h4> 
<h2> 
	Drag this into your bookmarklets toolbar:
	<a href="javascript: if(!(document.getElementById('ww_saving') || window.location.href.indexOf('wantworthy.com') &gt; -1 || window.location.href.match('about:blank'))){ var ifr = document.createElement('iframe'); ifr.id = &quot;ww_saving&quot;; ifr.setAttribute('style', &quot;width: 255px; height: 400px; position: fixed; top: 0; right: 0px; z-index: 10000001; margin: 0pt; background-color: white; border: 2px solid #202020 !important; overflow: hidden;&quot;); ifr.src = &quot;http://wantworthy.com/saving.html&quot;; document.body.appendChild( ifr ); void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('src','http://wantworthy.com/products.js?url='+encodeURIComponent(document.location.href)+'&amp;auth_token=6gsmhM2wTTVJL3coZsWH&amp;noCache='+new Date().getTime());document.body.appendChild(e)})())}
	" id="i_want_this_css3" onclick="return false;">+Jobby</a> 
</h2>

<li>Click this link: <a href="javascript:(function(){instacalc_script=document.createElement('SCRIPT');instacalc_script.type='text/javascript';instacalc_script.src='http://instacalc.com/gadget/instacalc.bookmarklet.js?x='+(Math.random());document.getElementsByTagName('head')[0].appendChild(instacalc_script);})();"style="border: 2px solid #999; padding: 2px; background: #cacaca; font-weight: bold;">instacalc bookmarklet</a>. </li>

<li>A cleaner bookmarklet link:
	<a href="javascript:(function(){jobby_script=document.createElement('SCRIPT');jobby_script.type='text/javascript';jobby_script.src='http://dl.dropbox.com/u/1906900/jobby.js';document.getElementsByTagName('head')[0].appendChild(jobby_script);})();" style="border: 2px solid #999; padding: 2px; background: #cacaca; font-weight: bold;">
		jobby v0.1
	</a>
</li>

<a href="javascript:(function(){var jsCode = document.createElement('script');jsCode.setAttribute('src', 'http://dl.dropbox.com/u/1906900/jobby.js?noCache='+new Date().getTime()');document.body.appendChild(jsCode);}());">Linkster</a>

<a href="javascript: alert('Linky text');">Linky</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobby</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :added %><br />
    <%= f.date_select :added %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <tr>
	<th>Date Added</th>
	<th>Position</th>
    <th>Company</th>
    <th>URL</th>
    <th>Priority</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>
    <td><%= listing.added %></td>
	<td><%= listing.position %></td>
    <td><%= listing.company %></td>
    <td><%= listing.url %></td>
    <td><%= listing.priority %></td>
    <td><%= listing.uid %></td>
    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @listing.company %>
</p>

<p>
  <b>Url:</b>
  <%= @listing.url %>
</p>

<p>
  <b>Added:</b>
  <%= @listing.added %>
</p>

<p>
  <b>Priority:</b>
  <%= @listing.priority %>
</p>

<p>
  <b>Uid:</b>
  <%= @listing.uid %>
</p>


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'Date Added' %><br />
    <%= f.date_select :dadded %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Date Added</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= user.dadded %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date Added:</b>
  <%= @user.dadded %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>